### ISSUE TITLE
ERROR: global_graph

### ISSUE THREAD

**Issue by awal-ahmed** [guanghuixu/AnchorCaptioner#13]
'global_graph' is missing in 'AnchorCaptioner/blob/main/configs/captioning/m4c_textcaps/m4c_captioner_coco.yml' file

**Comment by guanghuixu** [comment]
Do you want to run the TextCap model on COCO dataset?
The COCO dataset doesn't contain the OCR annotations, so that we cannot build the `global_graph` on it.
But you can modify a little code to run it.
For example, you can ignore the code which using `global_graph`.
I'm sorry about that, the experiments of COCO is our ablation and this repo cannot run it directly.
