### ISSUE TITLE
关于urllib3版本冲突的问题

### ISSUE THREAD

**Issue by zackhxn** [guanghuixu/AnchorCaptioner#8]
作者您好~
在运行
![QQ截图20211030091632](https://user-images.githubusercontent.com/65634324/139515140-1dd593b3-089d-48fa-904a-07c9e5abb246.png)
最后一步时，
![image](https://user-images.githubusercontent.com/65634324/139515166-30e85961-cbe9-4f49-a071-ccdd0bb22081.png)
出现了这样的问题，请问该如何解决呢？

**Comment by guanghuixu** [comment]
可以尝试安装提示的版本；使用建议使用python 3.6




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guanghuixu/AnchorCaptioner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 上午9:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[guanghuixu/AnchorCaptioner] 关于urllib3版本冲突的问题 (Issue #8)





 
作者您好~
 在运行
 
 最后一步时，
 
 出现了这样的问题，请问该如何解决呢？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
